version: '3'
services:
  proxy:
    image: docker.io/nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    networks:
      internal:
        ipv4_address: 192.168.1.100
      hostnet:
  mongo:
    image: docker.io/mongo
    networks:
      internal:
        ipv4_address: 192.168.1.2
  server:
    image: ghcr.io/blazej-smorawski/ask-projekt-server:latest
    networks:
      internal:
        ipv4_address: 192.168.1.3

networks:
  internal:
    external: true
  hostnet: